### ISSUE TITLE
Summary report has formatting errors

### ISSUE THREAD

**Issue by tomotvos** [thamara/vscode-code-annotation#37]
The summary report seems to mess up on formatting the code blocks. It looks like it is omitting a set of ``` between the source file name and the method being annotated. For example:

# Code Annotator - Summary

---
### - This should also be checking to make sure it is not a service token

Created at 2021-11-16 21:24
```
`Proxy/UtilityClasses/UserAuthorize.cs`

```

```
### - Authenticate should use the "EP" model the other endpoints are using

Created at 2021-11-16 21:32
```
`Proxy/Controllers/V2/customerController.cs`

```
Authenticate
```

**Comment by thamara** [comment]
Thank you for reporting this. The fix is in place and will be included in the next release of the extension (which should happen in about 15 days).
If you don't want to wait for the update from the VSCode marketplace, you can use [this link](https://github.com/thamara/vscode-code-annotation/blob/main/code-annotation-0.0.2-dev.vsix) and install it manually. For information how to install manually, check [this SO answer](https://stackoverflow.com/a/50232194).
