### ISSUE TITLE
Generate markdown summary without saving a file

### ISSUE THREAD

**Issue by thamara** [thamara/vscode-code-annotation#7]
`generateMarkdownReport` on `reporting.ts` generates the file only if a workspace is defined. This should be replaced by a virtual file, and the user can choose where to save it.

**Comment by taismassaro** [comment]
hi @thamara, I'd like to give this a try but have never developed a vscode extension 😁 could you give me some insights on where to start? I'm assuming [this](https://code.visualstudio.com/api/extension-guides/virtual-documents) would be useful documentation? thanks!

**Comment by thamara** [comment]
Sure! Go ahead! 
This is also my first vscode extension, so I'm learning too. hahahaha
This link is indeed good documentation, besides this, I usually go around GitHub looking for places where this is used (it helps if you already know of an extension that does this, but searching the code works well too). This is what I've been doing.
[This](https://stackoverflow.com/questions/41068197/vscode-create-unsaved-file-and-add-content) might also be a good approach.
My idea behind this is not to "invade" the user's workspace by automatically saving the file, but at the same time, it would be really good if the user could easily save it just like opening a new file in VSCode.

And thank you a lot for the feedback <3
Also, feel free to suggest any change that is not captured in the issues yet, this way you have priority :D

**Comment by taismassaro** [comment]
![image](https://user-images.githubusercontent.com/16339834/96167933-5a1aad80-0f20-11eb-8075-722e2d6ae6c3.png)

@thamara I'm getting this when clicking on the `summary` button both locally and on the extension installed via the .vsix file. do I need to do anything specific to create a workspace? always thought it was just a project folder.

---

unrelated to this issue: when I started going through the code and vscode documentation I came across the `command.category` and thought that might be a better solution instead of writing `Code Annotation` before the title for each command. that way, the `Code Annotation` prefix only shows up when using the **command palette**, but not as the name of each button in the panel, which in my opinion makes it look a bit cleaner. 

![image](https://user-images.githubusercontent.com/16339834/96168523-28eead00-0f21-11eb-85fd-3a6bfabbdd30.png)
*package.json*
![image](https://user-images.githubusercontent.com/16339834/96168856-ab776c80-0f21-11eb-8fcb-f4a3b1bbe16d.png)

do you think it makes sense? if yes, would it be ok for me to open a PR for this change? :)

**Comment by thamara** [comment]
> @thamara I'm getting this when clicking on the summary button both locally and on the extension installed via the .vsix file. do I need to do anything specific to create a workspace? always thought it was just a project folder.

Hmm, that's strange. Let me confirm and get back to you.

> do you think it makes sense? if yes, would it be ok for me to open a PR for this change? :)

Yes! Absolutally. I didn't know that existed. A PR for this would be more than welcome!

**Comment by Tim3W4rp** [comment]
Hey @thamara!
I just installed your extension and I love the simplicity.

One thing - how can I specify the place where to save the .md file? We would love to use this in our project to share notes between developers.

Thanks!

**Comment by thamara** [comment]
Hey @Tim3W4rp! Thanks for the feedback.
Looks like the only way today is to copy the content of the md file and save it elsewhere (which was my primary use case, so I didn't notice it).
I'll open an issue here in GH to improve this part of the extension and will try to work on it over the next days/weeks. :)

**Comment by fcFn** [comment]
Heh, I have a somewhat popular app here on GH myself and I understand that we all frequently lose interest in our pet projects. Anyway, that is a very minor annoyance that you have to press a button to close the file. I hope someday you will find time to fix this. Maybe the issue should be reopened meanwhile? 

Thanks for a great extension anyway!
